//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSAutoParabrisasNic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public int idProducto { get; set; }
        public int idMarca { get; set; }
        public int idPrecio { get; set; }
        public string descripcion { get; set; }
        public string codigoBarra { get; set; }
        public Nullable<int> cantidadEnStock { get; set; }
        public string numeroLote { get; set; }
        public bool estado { get; set; }
        public Nullable<System.DateTime> fechaVence { get; set; }
        public Nullable<System.DateTime> fechaRegistro { get; set; }
        public Nullable<System.DateTime> fechaUpdate { get; set; }
    }
}
